# DO NOT EDIT THIS FILE!
#
# Python module service__POA generated by omniidl

import omniORB
omniORB.updateModule("service__POA")

# ** 1. Stub files contributing to this module
import GameService_idl
import UserService_idl

# ** 2. Sub-modules

# ** 3. End
