# DO NOT EDIT THIS FILE!
#
# Python module service generated by omniidl

import omniORB
omniORB.updateModule("service")

# ** 1. Stub files contributing to this module
import GameService_idl
import UserService_idl

# ** 2. Sub-modules

# ** 3. End
class PlayerAccount:
    pass